"""initial_schema

Revision ID: e662a51ab537
Revises:
Create Date: 2026-05-17 01:17:38.217361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e662a51ab537'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auth_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_codes_email'), 'auth_codes', ['email'], unique=False)
    op.create_index('ix_auth_codes_email_used', 'auth_codes', ['email', 'used'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_token'), 'auth_sessions', ['token'], unique=True)
    op.create_table('fundraiser_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_houses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address_number', sa.String(length=20), nullable=True),
    sa.Column('street_name', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('full_address', sa.String(length=500), nullable=False),
    sa.Column('normalized_address', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('owner_name', sa.String(length=300), nullable=True),
    sa.Column('resident_name', sa.String(length=300), nullable=True),
    sa.Column('parcel_id', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('legal_description', sa.Text(), nullable=True),
    sa.Column('land_value', sa.Float(), nullable=True),
    sa.Column('improvement_value', sa.Float(), nullable=True),
    sa.Column('total_appraised_value', sa.Float(), nullable=True),
    sa.Column('property_type', sa.String(length=100), nullable=True),
    sa.Column('manually_created', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_master_houses_latlon', 'master_houses', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_master_houses_normalized', 'master_houses', ['normalized_address'], unique=False)
    op.create_index(op.f('ix_master_houses_normalized_address'), 'master_houses', ['normalized_address'], unique=False)
    op.create_index('ix_master_houses_parcel', 'master_houses', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_master_houses_zip_code'), 'master_houses', ['zip_code'], unique=False)
    op.create_table('scout_form_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('field_type', sa.String(length=30), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_key')
    )
    op.create_index('ix_scout_form_fields_position', 'scout_form_fields', ['position'], unique=False)
    op.create_table('scout_roster',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('scout_id', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_imports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('import_batch_id', sa.String(length=100), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_houses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['fundraiser_events.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['master_houses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'house_id', name='uq_event_house')
    )
    op.create_index('ix_event_houses_assigned_to', 'event_houses', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_event_houses_event_id'), 'event_houses', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_houses_house_id'), 'event_houses', ['house_id'], unique=False)
    op.create_index('ix_event_houses_status', 'event_houses', ['status'], unique=False)
    op.create_table('house_source_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('source_import_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_record_id', sa.String(length=200), nullable=True),
    sa.Column('source_last_updated', sa.DateTime(), nullable=True),
    sa.Column('import_batch_id', sa.String(length=100), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('match_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['master_houses.id'], ),
    sa.ForeignKeyConstraint(['source_import_id'], ['source_imports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('house_id', 'source_import_id', 'source_record_id', name='uq_house_source_link')
    )
    op.create_index(op.f('ix_house_source_links_house_id'), 'house_source_links', ['house_id'], unique=False)
    op.create_index(op.f('ix_house_source_links_source_import_id'), 'house_source_links', ['source_import_id'], unique=False)
    op.create_table('unmatched_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_import_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_record_id', sa.String(length=200), nullable=True),
    sa.Column('raw_address', sa.String(length=500), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('resolved_house_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_house_id'], ['master_houses.id'], ),
    sa.ForeignKeyConstraint(['source_import_id'], ['source_imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_house_id', sa.UUID(), nullable=False),
    sa.Column('visited_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('donation_amount', sa.Float(), nullable=True),
    sa.Column('tickets_purchased', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up', sa.Boolean(), nullable=True),
    sa.Column('volunteer_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('scout_name', sa.String(length=200), nullable=True),
    sa.Column('scout_id', sa.String(length=100), nullable=True),
    sa.Column('door_answer', sa.Boolean(), nullable=True),
    sa.Column('donation_given', sa.Boolean(), nullable=True),
    sa.Column('former_scout', sa.Boolean(), nullable=True),
    sa.Column('avoid_house', sa.Boolean(), nullable=True),
    sa.Column('custom_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_house_id'], ['event_houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_event_house_id'), 'visits', ['event_house_id'], unique=False)
    op.create_index('ix_visits_scout_name', 'visits', ['scout_name'], unique=False)
    op.create_index('ix_visits_visited_at', 'visits', ['visited_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_visits_visited_at', table_name='visits')
    op.drop_index('ix_visits_scout_name', table_name='visits')
    op.drop_index(op.f('ix_visits_event_house_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_table('unmatched_records')
    op.drop_index(op.f('ix_house_source_links_source_import_id'), table_name='house_source_links')
    op.drop_index(op.f('ix_house_source_links_house_id'), table_name='house_source_links')
    op.drop_table('house_source_links')
    op.drop_index('ix_event_houses_status', table_name='event_houses')
    op.drop_index(op.f('ix_event_houses_house_id'), table_name='event_houses')
    op.drop_index(op.f('ix_event_houses_event_id'), table_name='event_houses')
    op.drop_index('ix_event_houses_assigned_to', table_name='event_houses')
    op.drop_table('event_houses')
    op.drop_table('source_imports')
    op.drop_table('scout_roster')
    op.drop_index('ix_scout_form_fields_position', table_name='scout_form_fields')
    op.drop_table('scout_form_fields')
    op.drop_index(op.f('ix_master_houses_zip_code'), table_name='master_houses')
    op.drop_index('ix_master_houses_parcel', table_name='master_houses')
    op.drop_index(op.f('ix_master_houses_normalized_address'), table_name='master_houses')
    op.drop_index('ix_master_houses_normalized', table_name='master_houses')
    op.drop_index('ix_master_houses_latlon', table_name='master_houses')
    op.drop_table('master_houses')
    op.drop_table('fundraiser_events')
    op.drop_index(op.f('ix_auth_sessions_token'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index('ix_auth_codes_email_used', table_name='auth_codes')
    op.drop_index(op.f('ix_auth_codes_email'), table_name='auth_codes')
    op.drop_table('auth_codes')
    op.drop_table('allowed_emails')
    # ### end Alembic commands ###
